export let followers = [
	'2025th',
	'2025th Street',
	'Alexandria Jade 🖤',
	'Anice Teel',
	'Adriana🌞',
	'Andrew Guthrie',
	'Amanda',
	'Alex Peters',
	'A Person',
	'Aliya',
	'A-Ron the DJ',
	'Anomalous Designs LLC',
	'Adam Yarbrough',
	'Andrew M',
	'Benkidu',
	'Briauna C Benton',
	'Brian Weir',
	'Bill',
	'Brady V Jesser',
	'Barry Parks Jr',
	'Brooks Jarrett',
	'Black Dahlia Tattoo Co.',
	'Cameron Adams',
	'Cam Sprando',
	'Chris Cubbage',
	'Chris Hanson',
	'Cassie Guthrie McLaughlin',
	'Chance Frederick',
	'Colton Giorgianni',
	'Cember Friend 💍🎀',
	'Charles',
	'Cember Inks | Tattoo & Illustration',
	'Clancy Terry',
	'Daemon Lozano',
	'David Merry',
	'DENIS',
	'Dustin B Ready',
	'Darryl Pullman',
	'Derk',
	'Doug Terranova',
	'Daniel Kelly',
	'Duncan Clark Lmt',
	"Danny O'Connor",
	'Donna Fox',
	'Eric Carlson',
	'EATYOURSKIN',
	'E 🕷️',
	'Ellen Dooley',
	'Ervs',
	'Elias Alexander Watts',
	'Eric',
	'Ella Harter',
	'Followers',
	'George Rivera',
	'Greg Kauffman',
	'Heidi Incognito',
	'Ian Johnson',
	'Inactive',
	'Ivan Jay',
	'Josh Negrini',
	'Jake',
	'John R.',
	'Joey Almanza',
	'Jordan Catalano',
	'Jon Petty',
	'J',
	'JP Hardy',
	'J',
	'Joseph Lublink',
	'Justin Ruggieri',
	'Joshua',
	'Jeffrey Alexander',
	'Jorden Hall',
	'Josh Runyon',
	'Jarred Price',
	'Jake Turner',
	'Justin W',
	'Johnny Gilbert',
	'Jarred Woodworth',
	'Kristin Headley',
	'Katie Bennett',
	'Karsten Dejonge',
	'Koa',
	'Kayla Smith',
	'Kimberly Baum',
	'Keep Portland Tatted!',
	'K',
	'Lance Eads',
	'Le Brave qui pique',
	'Legaoaituanai Noa Stowers',
	'Lauren Kayarian',
	'Lia 🧿',
	'Lea',
	'Lorren Snowwolf',
	'Myla !!',
	'Maddi',
	'Matt Dobbins',
	'Matthew Miller',
	'Mat Davidson',
	'Mark Sutton',
	'Maya Lusion',
	'Malcolm Facione',
	'Mateo Gruber',
	'Maisey McKinney',
	'M. Ajootian',
	'Maisey McKinney',
	'Matt Rumley',
	'Miz Larry',
	'Michael Golisek',
	'Matt Koltermann',
	'Matthew J Black',
	'Morgan🩷 | PDX Lash & Brow Artist',
	'Morgan Moon',
	'Mario Viele',
	'Mike Wartgow',
	'Matthew Beermann',
	'Matthew Alan',
	'Matt Vegas',
	'Nikole Deitering',
	'Nic Castaneda',
	'Nate Spear',
	'Nick Ball',
	'Nick Crockett',
	'OHKOFA🏀☔️🌎',
	'Pip Miller',
	'Patrick Spurrier',
	'Pedro Sinhorini',
	'Portland Sleestak',
	'Rj Ouzts',
	'Rat Barse',
	'Rey🙊',
	'Ryker',
	'Raven Procknow',
	'Roy perterson',
	'Roman',
	'Roy Fryer',
	'Restorative Earth Bodywork',
	'Richard Schader',
	'RayRay Nolastnames',
	'Search',
	'Search',
	'Swift Joel Jolly Springer',
	'Sunray Gmeiner-Perez',
	'Sarah Jane Marie Laur',
	'Sierra',
	'Sword and/or Clint',
	'Sean Allen Lamb',
	'Shawn Telkamp',
	'Sebastian',
	'Trenton Dean Flood',
	'Tim Konze',
	'Thomas Owens-Wink',
	'Tony Ruiz',
	'Tony Bermudez',
	'Tina 🌱✨',
	'Thom Palmer',
	'Tre Keough',
	'Tucker Max',
	'Tom',
	'Travis Smith',
	'Valerie',
	'Wayne Bund',
	'Wing 🪽',
	'Zack Rebarchek',
	'_feral.scum',
	'annabelle_lecter',
	'alexapart5_3000',
	'alexa',
	'alex.nyx.jade',
	'anice.nikole',
	'ajootian.inks',
	'artony_tattoo',
	'aaron.person.duh',
	'angelstarbabi',
	'a.ron.the.dj.pdx',
	'anomalous_designs',
	'adam.yarbrough',
	'accidental.scifi',
	'asdf.asdf.asdf.99',
	'asdf',
	'aggressive_blindspots',
	'art_nerd_circa_1983',
	'benkidu',
	'birdseye_tattoo',
	'books.with.abra',
	'bearofportland',
	'briaunabenton',
	'brian.weir',
	'berma051',
	'bigsissytattoo',
	'bigmattjr',
	'barryparksjr',
	'buddy norman',
	'brisingroftoth',
	'bundlandia',
	'black_dahlia_tattoo_co_',
	'bluwoof1986',
	'chaoticevil.sh1t',
	'cjadamspdx',
	'cam___bam',
	'cubbage.christopher',
	'crickkettt',
	'chanson202',
	'corvidcreature',
	'cubjon85',
	'chainstitch.nick',
	'ckguthrie',
	'cemberf',
	'charleycarrick',
	'cemberinks',
	'crowstealsfire',
	'coin_operated',
	'drgooby',
	'djkittykisser',
	'dae_me_on',
	'dawnstrike55',
	'dasmurph85',
	'denis_lewain',
	'depiedefermo',
	'dudeimsj',
	'derk_asaurus',
	'dougterranova',
	'djskype',
	'danieldoesink',
	'duncduncpdx',
	'disaffect',
	'eyos_organics',
	'ellen_snail',
	'everybodylovesregob',
	'eliasalexwatts',
	'fauxcochon',
	'fartliquorz',
	'fleetwoodtatt',
	'funtaye',
	'gmeinerray',
	'gilbo_fagguns',
	'heybabes298',
	'h0tsh0rtssound',
	'halflingbards',
	'helenofboy',
	'halfguarddog',
	'itcanonlybejaaared',
	'its_me_jordan_catalano',
	'irvs_bailamas',
	'ivana.ink.tatts.llc',
	'jakeovertimetattoos',
	'juniper 𓆉︎ ☼ 𓇼 ☼ ꩜',
	'jtrche',
	'jalmanztea',
	'jphardyofficial',
	'johnny_chaos23',
	'jjlublin',
	'josephinebeanbottom',
	'joshfries',
	'jarredprice1989',
	'jarredwoodworth',
	'kristinheadley',
	'kookykatie',
	'katie',
	'kindly.kari_',
	'koa_jimenez03',
	'koolkatman',
	'kayla.smith.420',
	'kvlemcclvng',
	'keep_portland_tatted',
	'kaycee0660',
	'kuarch',
	'little_kestrel_apothecary',
	'little kestrel apothecary',
	'lance_eads',
	'leastfamouspersonever',
	'lebravequipique',
	'legatoshinuiano',
	'laurenkayarian',
	'leaanderthal',
	'librarianzaddy',
	'langdonalger_',
	'lorren_snowwolf',
	'likethecrab',
	'mattinthehat267',
	'mattdobbins',
	'mat_davidson.tattoo',
	'markthehunter1992',
	'maya.lusion.tattoo',
	'mortonsen',
	'mothmansgf04',
	'm.faeshin_er',
	'melody.p.23',
	'mister_univers',
	'mizlarry',
	'mikieegol',
	'mattkoltermann',
	'morganicspdx_',
	'moon_goof_tattoo',
	'mario.viele',
	'mwartgow',
	'matthewbeermann',
	'not_bill_nye',
	'nerotheotter',
	'nicholas',
	'nailsbycrickkettt',
	'natespearart',
	'nerd_zen84',
	'owenswink',
	'pup_oengus',
	'pdxcigarvet',
	'puppaluffagus',
	'pup.pokes',
	'pdxclancy',
	'portlandsleestak',
	'reyzw0rld',
	'ryk.e_r',
	'roy.perterson',
	'raiseyourblade',
	'ryanmcfag',
	'roy1188',
	'restorative_earth_bodywork',
	'sunbear78',
	'swift_springer',
	'spurrierpatrick',
	'snickeldick',
	'sparknandf',
	'see2me2252',
	'string.of.hearts.ink',
	'seaniscooliguess',
	'seabro92',
	'soggysockstattoos',
	'stargirlstattoo',
	'stella price',
	'skecherkid',
	'trentonflood',
	'tckonze',
	'the_rat_tattoo',
	'tattoosbypip',
	'traumaticbrainink',
	'tink_erhell',
	'tinaann242',
	'taliaivins',
	'trekeough',
	'tucker_pdmax',
	'tobbins.exe',
	'tattoosbyps',
	'taM nanabalaM',
	'town79',
	'untitledcannabisproject',
	'valpal5',
	'viridianvalor',
	'veshengro',
	'vitadelizioso',
	'vegasvip',
	'woodybanx',
	'xanderpete',
	'xjg2',
	'yourfavburrito',
	'ztrski',
	'☹︎ 𝕲𝖜𝖊𝖓𝖞𝖙𝖍 ☹︎',
	'🌻𝙼𝚎𝚕𝚘𝚍𝚢🌻',
	'🌸stella🌸',
	'🖤📚 Abra Shipley 📚🖤',
	'🦇M🦇'
];
export let following = [
	'2025th',
	'2025th Street',
	'Alexandria Jade 🖤',
	'Anice Teel',
	'Adriana🌞',
	'Andrew Guthrie',
	'Amanda',
	'Alex Peters',
	'A Person',
	'Aliya',
	'A-Ron the DJ',
	'Anomalous Designs LLC',
	'Adam Yarbrough',
	'Andrew M',
	'Benkidu',
	'Briauna C Benton',
	'Brian Weir',
	'Bill',
	'Brady V Jesser',
	'Barry Parks Jr',
	'Brooks Jarrett',
	'Black Dahlia Tattoo Co.',
	'Cameron Adams',
	'Cam Sprando',
	'Chris Cubbage',
	'Chris Hanson',
	'Cassie Guthrie McLaughlin',
	'Chance Frederick',
	'Colton Giorgianni',
	'Cember Friend 💍🎀',
	'Charles',
	'Cember Inks | Tattoo & Illustration',
	'Clancy Terry',
	'Daemon Lozano',
	'David Merry',
	'DENIS',
	'Dustin B Ready',
	'Darryl Pullman',
	'Derk',
	'Doug Terranova',
	'Daniel Kelly',
	'Duncan Clark Lmt',
	"Danny O'Connor",
	'Donna Fox',
	'Eric Carlson',
	'EATYOURSKIN',
	'E 🕷️',
	'Ellen Dooley',
	'Ervs',
	'Elias Alexander Watts',
	'Eric',
	'Ella Harter',
	'George Rivera',
	'Greg Kauffman',
	'Heidi Incognito',
	'Ian Johnson',
	'Inactive',
	'Ivan Jay',
	'Josh Negrini',
	'Jake',
	'John R.',
	'Joey Almanza',
	'Jordan Catalano',
	'Jon Petty',
	'J',
	'JP Hardy',
	'J',
	'Joseph Lublink',
	'Justin Ruggieri',
	'Joshua',
	'Jeffrey Alexander',
	'Jorden Hall',
	'Josh Runyon',
	'Jarred Price',
	'Jake Turner',
	'Justin W',
	'Johnny Gilbert',
	'Jarred Woodworth',
	'Kristin Headley',
	'Katie Bennett',
	'Karsten Dejonge',
	'Koa',
	'Kayla Smith',
	'Kimberly Baum',
	'Keep Portland Tatted!',
	'K',
	'Lance Eads',
	'Le Brave qui pique',
	'Legaoaituanai Noa Stowers',
	'Lauren Kayarian',
	'Lia 🧿',
	'Lea',
	'Lorren Snowwolf',
	'Myla !!',
	'Maddi',
	'Matt Dobbins',
	'Matthew Miller',
	'Mat Davidson',
	'Mark Sutton',
	'Maya Lusion',
	'Malcolm Facione',
	'Mateo Gruber',
	'Maisey McKinney',
	'M. Ajootian',
	'Maisey McKinney',
	'Matt Rumley',
	'Miz Larry',
	'Michael Golisek',
	'Matt Koltermann',
	'Matthew J Black',
	'Morgan🩷 | PDX Lash & Brow Artist',
	'Morgan Moon',
	'Mario Viele',
	'Mike Wartgow',
	'Matthew Beermann',
	'Matthew Alan',
	'Matt Vegas',
	'Nikole Deitering',
	'Nic Castaneda',
	'Nate Spear',
	'Nick Ball',
	'Nick Crockett',
	'OHKOFA🏀☔️🌎',
	'Pip Miller',
	'Patrick Spurrier',
	'Pedro Sinhorini',
	'Portland Sleestak',
	'Rj Ouzts',
	'Rat Barse',
	'Rey🙊',
	'Ryker',
	'Raven Procknow',
	'Roy perterson',
	'Roman',
	'Roy Fryer',
	'Restorative Earth Bodywork',
	'Richard Schader',
	'RayRay Nolastnames',
	'Swift Joel Jolly Springer',
	'Sunray Gmeiner-Perez',
	'Sarah Jane Marie Laur',
	'Sierra',
	'Sword and/or Clint',
	'Sean Allen Lamb',
	'Shawn Telkamp',
	'Sebastian',
	'Trenton Dean Flood',
	'Tim Konze',
	'Thomas Owens-Wink',
	'Tony Ruiz',
	'Tony Bermudez',
	'Tina 🌱✨',
	'Thom Palmer',
	'Tre Keough',
	'Tucker Max',
	'Tom',
	'Travis Smith',
	'Valerie',
	'Wayne Bund',
	'Wing 🪽',
	'Zack Rebarchek',
	'_feral.scum',
	'annabelle_lecter',
	'alexapart5_3000',
	'alexa',
	'alex.nyx.jade',
	'anice.nikole',
	'ajootian.inks',
	'artony_tattoo',
	'aaabradyvjesser',
	'aaron.person.duh',
	'angelstarbabi',
	'a.ron.the.dj.pdx',
	'anomalous_designs',
	'adam.yarbrough',
	'accidental.scifi',
	'asdf.asdf.asdf.99',
	'asdf',
	'aggressive_blindspots',
	'art_nerd_circa_1983',
	'benkidu',
	'birdseye_tattoo',
	'books.with.abra',
	'bearofportland',
	'briaunabenton',
	'brian.weir',
	'berma051',
	'bigsissytattoo',
	'bigmattjr',
	'barryparksjr',
	'buddy norman',
	'brisingroftoth',
	'bundlandia',
	'black_dahlia_tattoo_co_',
	'bluwoof1986',
	'chaoticevil.sh1t',
	'cjadamspdx',
	'cam___bam',
	'cubbage.christopher',
	'crickkettt',
	'chanson202',
	'corvidcreature',
	'cubjon85',
	'chainstitch.nick',
	'ckguthrie',
	'cemberf',
	'charleycarrick',
	'cemberinks',
	'crowstealsfire',
	'coin_operated',
	'drgooby',
	'djkittykisser',
	'dae_me_on',
	'dawnstrike55',
	'dasmurph85',
	'denis_lewain',
	'depiedefermo',
	'dudeimsj',
	'derk_asaurus',
	'dougterranova',
	'djskype',
	'danieldoesink',
	'duncduncpdx',
	'disaffect',
	'eyos_organics',
	'ellen_snail',
	'everybodylovesregob',
	'eliasalexwatts',
	'fauxcochon',
	'fartliquorz',
	'fleetwoodtatt',
	'funtaye',
	'gmeinerray',
	'gilbo_fagguns',
	'heybabes298',
	'h0tsh0rtssound',
	'halflingbards',
	'helenofboy',
	'halfguarddog',
	'itcanonlybejaaared',
	'its_me_jordan_catalano',
	'irvs_bailamas',
	'ivana.ink.tatts.llc',
	'jakeovertimetattoos',
	'juniper 𓆉︎ ☼ 𓇼 ☼ ꩜',
	'jtrche',
	'jalmanztea',
	'jphardyofficial',
	'johnny_chaos23',
	'jjlublin',
	'josephinebeanbottom',
	'joshfries',
	'jarredprice1989',
	'jarredwoodworth',
	'kristinheadley',
	'kookykatie',
	'katie',
	'kindly.kari_',
	'koa_jimenez03',
	'koolkatman',
	'kayla.smith.420',
	'keep_portland_tatted',
	'kaycee0660',
	'kuarch',
	'little_kestrel_apothecary',
	'little kestrel apothecary',
	'lance_eads',
	'leastfamouspersonever',
	'lebravequipique',
	'legatoshinuiano',
	'laurenkayarian',
	'leaanderthal',
	'librarianzaddy',
	'langdonalger_',
	'lorren_snowwolf',
	'likethecrab',
	'mattinthehat267',
	'mattdobbins',
	'mat_davidson.tattoo',
	'markthehunter1992',
	'maya.lusion.tattoo',
	'mortonsen',
	'mothmansgf04',
	'm.faeshin_er',
	'mister_univers',
	'mizlarry',
	'mikieegol',
	'mattkoltermann',
	'morganicspdx_',
	'moon_goof_tattoo',
	'mario.viele',
	'mwartgow',
	'matthewbeermann',
	'not_bill_nye',
	'nerotheotter',
	'nicholas',
	'nailsbycrickkettt',
	'natespearart',
	'nerd_zen84',
	'owenswink',
	'pup_oengus',
	'pdxcigarvet',
	'puppaluffagus',
	'pup.pokes',
	'pdxclancy',
	'portlandsleestak',
	'reyzw0rld',
	'ryk.e_r',
	'roy.perterson',
	'raiseyourblade',
	'ryanmcfag',
	'roy1188',
	'restorative_earth_bodywork',
	'sunbear78',
	'swift_springer',
	'spurrierpatrick',
	'snickeldick',
	'sparknandf',
	'see2me2252',
	'string.of.hearts.ink',
	'seaniscooliguess',
	'seabro92',
	'soggysockstattoos',
	'stargirlstattoo',
	'stella price',
	'skecherkid',
	'trentonflood',
	'tckonze',
	'the_rat_tattoo',
	'tattoosbypip',
	'traumaticbrainink',
	'tink_erhell',
	'tinaann242',
	'taliaivins',
	'trekeough',
	'tucker_pdmax',
	'tobbins.exe',
	'tattoosbyps',
	'taM nanabalaM',
	'town79',
	'untitledcannabisproject',
	'valpal5',
	'viridianvalor',
	'veshengro',
	'vitadelizioso',
	'vegasvip',
	'woodybanx',
	'xanderpete',
	'xjg2',
	'yourfavburrito',
	'ztrski',

	'☹︎ 𝕲𝖜𝖊𝖓𝖞𝖙𝖍 ☹︎',
	'🌸stella🌸',
	'🖤📚 Abra Shipley 📚🖤',
	'🦇M🦇'
];
